### ISSUE TITLE
Thanks for your umi-18.1 porject

### ISSUE THREAD

**Issue by aoaoemoji** [yarpiin/device_xiaomi_sm8250_common#2]
so can you tell me your tg？you can send email to me 741500926@qq.com thanks！
i just want to leran for you
now i am make flyme 9 android 11 use your los18.1 vendor！
so good！
thanks！

**Comment by yarpiin** [comment]
> so can you tell me your tg？you can send email to me [741500926@qq.com](mailto:741500926@qq.com) thanks！
> i just want to leran for you
> now i am make flyme 9 android 11 use your los18.1 vendor！
> so good！
> thanks！

you can find me on tg under @yarpiin
