### ISSUE TITLE
[Lineage OS] NFC restarts infinitely when trying to read a tag

### ISSUE THREAD

**Issue by schqual** [yarpiin/device_xiaomi_sm8250_common#8]
Hello. Thank you for your work!

I have an issue with NFC. When placing NFC tag at phone back nothing happens. If go to Settings - NFC while tag is attached infinite toggling NFC setting appears.

[Here's logcat](https://github.com/yarpiin/android_device_xiaomi_umi/files/6910907/logcat_07-31-2021_11-28-47.txt)

Device: umi (Mi 10)
Build: Lineage OS 20210730
GApps: open_gapps-arm64-11.0-nano-20210731
Magisk v23.0
FW: fw_umi_miui_UMI_V12.5.5.0.RJBCNXM_8fa4752ff3_11.0 (flashed before LOS zip, but seems it's still unnecessary following previous instructions on Telegram channel)
Clean flash, formatted data, no apps installed.

**Comment by yarpiin** [comment]
Use different gapps and remove magisk and try to reproduce. Oh and try reflash firmware after the rom. My builds have firmware built in, but some individuals have issues like that and more likley it is firmware related , clean flash rom then firmware and see

**Comment by schqual** [comment]
Tried this variants (in order of zips flashing):
- los zip then fw (no gapps or magisk, formatted and wiped all before flashing)
- los zip only (formatted and wiped all before flashing again)

The issue still occurs

**Comment by yarpiin** [comment]
just checked with other users and you are the only one unfortunate affeaid

**Comment by schqual** [comment]
Weird. But that issue presents on latest Evolution X, but on last Pixel Experience NFC works properly.
Tried more different fw 12.5.3/12.2.2 with clean flash. Evo/LOS still have this bug. And PE anytime works fine. Seems like some source updates? I see in lash change logs following line:
> * sm8250-common: Switch to source built NFC
My log says this is a problem with libnfc-nci.so.

And more: I tried to flash by fastboot official MIUI package V12.5.2.0.RJBEUXM with bootloader locking and following unlocking/flashin twrp/roms procedure - this issui still happens on EvoX.

Is there any additional info required?

**Comment by yarpiin** [comment]
As I said earlier , no one else reported such issues. If you use any mods , custom kernel , magisk remove them . If it presist send me full logs please.

**Comment by schqual** [comment]
No mods, no magisk, no any additional packages as I said earlier. Logs in first post. It's not full?

**Comment by schqual** [comment]
Look - same problem https://t.me/mi10aosp/50412
